version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "05:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
      - "automerge"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "05:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
      - "automerge"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "05:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "docker"
      - "automerge"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
