name: Docker Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      push:
        description: "Push image to registry (true/false)"
        required: true
        default: false
        type: boolean
      tag:
        description: "Image tag to use for manual builds (e.g., dev-123)"
        required: false
        type: string

concurrency:
  group: docker-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: Build Docker image (push on tag or when requested)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Determine if push
        id: should_push
        shell: bash
        env:
          IS_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
          DISPATCH_PUSH: ${{ github.event_name == 'workflow_dispatch' && inputs.push }}
        run: |
          if [[ "${IS_TAG}" == "true" || "${DISPATCH_PUSH}" == "true" ]]; then
            echo "push=true" >> "$GITHUB_OUTPUT"
          else
            echo "push=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: steps.should_push.outputs.push == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Tag push: keep the 'v' tag (e.g., v1.2.3)
            type=ref,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            # Semver variants (without the 'v' prefix): 1.2.3, 1.2, 1
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            # Manual dispatch: explicit tag if provided
            type=raw,value=${{ inputs.tag }},enable=${{ github.event_name == 'workflow_dispatch' && inputs.tag != '' }}
            # Always include a content-addressable tag for traceability
            type=sha

      - name: Build and (optionally) push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ steps.should_push.outputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
